//! Agent-client asset installation and doctor reporting.

use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

const AGENT_SKILL_CONTENT: &str = include_str!("../../skills/SKILL.org");
const CODEX_DIR: &str = ".codex";
const CODEX_GUARD_BIN_DIR: &str = ".codex/rs-harness/bin";
const CODEX_GUARD_ENV: &str = ".codex/rs-harness/env.sh";
const CODEX_GUARD_TOOLS: &[&str] = &[
    "rtk", "rg", "grep", "fd", "find", "cat", "sed", "nl", "head", "tail", "awk", "bat", "less",
    "more",
];
const CODEX_SKILL_DIR: &str = ".codex/skills/rs-harness";
const CODEX_CONFIG: &str = ".codex/config.toml";
const CODEX_POLICY_PATH: &str = ".codex/harness-policy.json";
const CODEX_TOOL_MATCHER: &str =
    "Read|read_file|mcp__.*__read.*|Bash|exec_command|apply_patch|Edit|Write";
const CODEX_CONFIG_HOOK_COUNT: usize = 8;
const CODEX_CONFIG_HOOK_EVENTS: &[&str] = &[
    "SessionStart",
    "UserPromptSubmit",
    "PreToolUse",
    "PermissionRequest",
    "PostToolUse",
    "SubagentStart",
    "SubagentStop",
    "Stop",
];
const AGENT_POLICY_CONTENT: &str = r#"{
  "profiles": {
    "rust": {
      "enabled": true,
      "prime_required_before_edit": true,
      "raw_search_requires_ingest": true,
      "changed_check_required": true
    },
    "typescript": {
      "enabled": true,
      "prime_required_before_edit": true,
      "raw_search_requires_ingest": true,
      "changed_check_required": true
    }
  },
  "global": {
    "raw_ast_grep_blocked": true,
    "exact_file_edit_exception": true,
    "docs_only_exception": true
  }
}
"#;

pub(super) fn install_agent_assets(project_root: &Path, client: &str) -> Result<(), String> {
    if client != "codex" {
        return Err(format!("unsupported agent client: {client}"));
    }
    let skill_dir = project_root.join(CODEX_SKILL_DIR);
    let policy_path = project_root.join(CODEX_POLICY_PATH);
    let config_path = project_root.join(CODEX_CONFIG);
    fs::create_dir_all(project_root.join(CODEX_DIR))
        .map_err(|error| format!("failed to create codex dir: {error}"))?;
    fs::create_dir_all(&skill_dir)
        .map_err(|error| format!("failed to create agent skill dir: {error}"))?;
    fs::write(skill_dir.join("SKILL.org"), AGENT_SKILL_CONTENT)
        .map_err(|error| format!("failed to write agent skill: {error}"))?;
    fs::write(policy_path, AGENT_POLICY_CONTENT)
        .map_err(|error| format!("failed to write agent hook policy: {error}"))?;
    fs::write(config_path, agent_config_toml())
        .map_err(|error| format!("failed to write codex config.toml: {error}"))?;
    install_guard_shims(project_root)?;
    Ok(())
}

fn install_guard_shims(project_root: &Path) -> Result<(), String> {
    let guard_bin = project_root.join(CODEX_GUARD_BIN_DIR);
    fs::create_dir_all(&guard_bin)
        .map_err(|error| format!("failed to create agent guard bin dir: {error}"))?;
    for tool in CODEX_GUARD_TOOLS {
        let path = guard_bin.join(tool);
        fs::write(&path, guard_shim_script(tool))
            .map_err(|error| format!("failed to write agent guard shim {tool}: {error}"))?;
        make_executable(&path)?;
    }
    fs::write(project_root.join(CODEX_GUARD_ENV), guard_env_script())
        .map_err(|error| format!("failed to write agent guard env script: {error}"))?;
    Ok(())
}

fn guard_shim_script(tool: &str) -> String {
    format!(
        r#"#!/usr/bin/env sh
set -eu

tool="{tool}"
repo_root="${{RS_HARNESS_PROJECT_ROOT:-$(pwd)}}"
rs-harness agent guard --client codex "$repo_root" -- "$tool" "$@" || exit $?

self_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
clean_path=""
old_ifs=$IFS
IFS=:
for entry in ${{PATH:-}}; do
  if [ "$entry" = "$self_dir" ]; then
    continue
  fi
  if [ -z "$clean_path" ]; then
    clean_path=$entry
  else
    clean_path=$clean_path:$entry
  fi
done
IFS=$old_ifs
export PATH=$clean_path
exec "$tool" "$@"
"#
    )
}

fn guard_env_script() -> &'static str {
    r#"# Source from the repository root to route raw shell/RTK reads through rs-harness.
rs_harness_guard_bin="$(pwd)/.codex/rs-harness/bin"
case ":${PATH:-}:" in
  *":$rs_harness_guard_bin:"*) ;;
  *) export PATH="$rs_harness_guard_bin:${PATH:-}" ;;
esac
"#
}

#[cfg(unix)]
fn make_executable(path: &Path) -> Result<(), String> {
    let mut permissions = fs::metadata(path)
        .map_err(|error| format!("failed to stat agent guard shim: {error}"))?
        .permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(path, permissions)
        .map_err(|error| format!("failed to chmod agent guard shim: {error}"))
}

#[cfg(not(unix))]
fn make_executable(_path: &Path) -> Result<(), String> {
    Ok(())
}

fn agent_config_toml() -> String {
    format!(
        r#"# Generated by `rs-harness agent install --client codex`.
#
# Search-first flow:
# - Rust source reads are routed through rs-harness search packets.
# - Subagents should receive bounded search commands, not raw file inventories.
# - Pipe broad external candidates into `rs-harness search ingest items tests`.
# - Run one search command at a time; do not chain denied-read recovery commands.
# - Shells that bypass hook runtime can source `.codex/rs-harness/env.sh`.

[[hooks.SessionStart]]
matcher = "startup|resume|clear|compact"

[[hooks.SessionStart.hooks]]
type = "command"
timeout = 5
statusMessage = "Loading rs-harness search protocol"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex session-start "$repo_root"
'''

[[hooks.UserPromptSubmit]]

[[hooks.UserPromptSubmit.hooks]]
type = "command"
timeout = 5
statusMessage = "Planning rs-harness search flow"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex user-prompt "$repo_root"
'''

[[hooks.PreToolUse]]
matcher = "{CODEX_TOOL_MATCHER}"

[[hooks.PreToolUse.hooks]]
type = "command"
timeout = 5
statusMessage = "Checking rs-harness search flow"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex pre-tool "$repo_root"
'''

[[hooks.PermissionRequest]]
matcher = "{CODEX_TOOL_MATCHER}"

[[hooks.PermissionRequest.hooks]]
type = "command"
timeout = 5
statusMessage = "Checking rs-harness approval flow"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex permission-request "$repo_root"
'''

[[hooks.PostToolUse]]
matcher = "{CODEX_TOOL_MATCHER}"

[[hooks.PostToolUse.hooks]]
type = "command"
timeout = 5
statusMessage = "Updating rs-harness search flow state"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex post-tool "$repo_root"
'''

[[hooks.SubagentStart]]
matcher = ".*"

[[hooks.SubagentStart.hooks]]
type = "command"
timeout = 5
statusMessage = "Preparing rs-harness subagent context"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex subagent-start "$repo_root"
'''

[[hooks.SubagentStop]]
matcher = ".*"

[[hooks.SubagentStop.hooks]]
type = "command"
timeout = 5
statusMessage = "Checking rs-harness subagent evidence"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex subagent-stop "$repo_root"
'''

[[hooks.Stop]]

[[hooks.Stop.hooks]]
type = "command"
timeout = 5
statusMessage = "Checking rs-harness changed files"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex stop "$repo_root"
'''
"#
    )
}

pub(super) fn print_agent_doctor(
    project_root: &Path,
    action: &str,
    client: Option<&str>,
) -> Result<(), String> {
    let Some(client) = client else {
        println!(
            "[agent-doctor] action={action} client=none skill=false policy=false config=false hooks=0 daemon=missing protocol=cli-cold"
        );
        println!(
            "|note kind=client-required message=\"pass --client codex to inspect Codex assets\""
        );
        return Ok(());
    };
    if client != "codex" {
        return Err(format!("unsupported agent client: {client}"));
    }
    let skill = project_root.join(CODEX_SKILL_DIR).join("SKILL.org");
    let policy = project_root.join(CODEX_POLICY_PATH);
    let config = project_root.join(CODEX_CONFIG);
    let guard_bin = project_root.join(CODEX_GUARD_BIN_DIR);
    let guard_env = project_root.join(CODEX_GUARD_ENV);
    let config_exists = config.exists();
    println!(
        "[agent-doctor] action={action} client=codex skill={} policy={} config={} hooks={} guardBin={} guardEnv={} daemon=missing protocol=cli-cold",
        skill.exists(),
        policy.exists(),
        config_exists,
        if config_exists {
            CODEX_CONFIG_HOOK_COUNT
        } else {
            0
        },
        guard_bin.exists(),
        guard_env.exists()
    );
    println!(
        "|skill {} present={}",
        display_cli_path(project_root, &skill),
        skill.exists()
    );
    println!(
        "|policy {} present={}",
        display_cli_path(project_root, &policy),
        policy.exists()
    );
    println!(
        "|config {} present={}",
        display_cli_path(project_root, &config),
        config_exists
    );
    println!(
        "|guard-bin {} present={}",
        display_cli_path(project_root, &guard_bin),
        guard_bin.exists()
    );
    println!(
        "|guard-env {} present={}",
        display_cli_path(project_root, &guard_env),
        guard_env.exists()
    );
    for event in CODEX_CONFIG_HOOK_EVENTS {
        println!("|hook event={event} source=config present={config_exists}");
    }
    Ok(())
}

fn display_cli_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .display()
        .to_string()
        .replace('\\', "/")
}
