//! Agent-client asset installation and doctor reporting.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const AGENT_SKILL_CONTENT: &str = include_str!("../../skills/SKILL.org");
const CODEX_DIR: &str = ".codex";
const CODEX_SKILL_DIR: &str = ".codex/skills/rs-harness";
const CODEX_CONFIG: &str = ".codex/config.toml";
const CODEX_POLICY_PATH: &str = ".codex/harness-policy.json";
const DEFAULT_CODEX_PROFILE: &str = "rs-harness";
const RS_HARNESS_BLOCK_BEGIN: &str = "# BEGIN rs-harness agent hooks";
const RS_HARNESS_BLOCK_END: &str = "# END rs-harness agent hooks";
const CODEX_TOOL_MATCHER: &str = ".*(Read|readFile|readDirectory|read_file|FsReadFile|FsReadDirectory|fs\\\\.read|fs\\\\.readDirectory|fs/readFile|fs/readDirectory|fs\\\\.readbin|writeFile|FsWriteFile|fs\\\\.write|fs/write|fs\\\\.writeFile|fs/writeFile|FsRemove|fs\\\\.remove|fs/remove|FsCopy|fs\\\\.copy|fs/copy|fs\\\\.rename|fs/rename|mcp__.*__read.*|Bash|exec_command|command_execution|apply_patch|Edit|Write).*";
const CODEX_CONFIG_HOOK_COUNT: usize = 8;
const CODEX_CONFIG_HOOK_EVENTS: &[&str] = &[
    "SessionStart",
    "UserPromptSubmit",
    "PreToolUse",
    "PermissionRequest",
    "PostToolUse",
    "SubagentStart",
    "SubagentStop",
    "Stop",
];
const AGENT_POLICY_CONTENT: &str = r#"{
  "profiles": {
    "rust": {
      "enabled": true,
      "prime_required_before_edit": true,
      "raw_search_requires_ingest": true,
      "changed_check_required": true
    },
    "typescript": {
      "enabled": true,
      "prime_required_before_edit": true,
      "raw_search_requires_ingest": true,
      "changed_check_required": true
    }
  },
  "global": {
    "raw_ast_grep_blocked": true,
    "exact_file_edit_exception": true,
    "docs_only_exception": true
  }
}
"#;

#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub(super) enum AgentConfigScope {
    #[default]
    Project,
    CodexProfile(String),
}

impl AgentConfigScope {
    pub(super) fn codex_profile(profile: Option<String>) -> Result<Self, String> {
        let profile = profile.unwrap_or_else(|| DEFAULT_CODEX_PROFILE.to_string());
        validate_codex_profile_name(&profile)?;
        Ok(Self::CodexProfile(profile))
    }

    fn label(&self) -> &'static str {
        match self {
            Self::Project => "project",
            Self::CodexProfile(_) => "profile",
        }
    }

    pub(super) fn profile_name(&self) -> Option<&str> {
        match self {
            Self::Project => None,
            Self::CodexProfile(profile) => Some(profile),
        }
    }
}

pub(super) fn default_codex_profile_name() -> &'static str {
    DEFAULT_CODEX_PROFILE
}

pub(super) fn install_agent_assets(
    project_root: &Path,
    client: &str,
    scope: &AgentConfigScope,
) -> Result<(), String> {
    if client != "codex" {
        return Err(format!("unsupported agent client: {client}"));
    }
    let skill_dir = project_root.join(CODEX_SKILL_DIR);
    let policy_path = project_root.join(CODEX_POLICY_PATH);
    fs::create_dir_all(project_root.join(CODEX_DIR))
        .map_err(|error| format!("failed to create codex dir: {error}"))?;
    fs::create_dir_all(&skill_dir)
        .map_err(|error| format!("failed to create agent skill dir: {error}"))?;
    fs::write(skill_dir.join("SKILL.org"), AGENT_SKILL_CONTENT)
        .map_err(|error| format!("failed to write agent skill: {error}"))?;
    fs::write(policy_path, AGENT_POLICY_CONTENT)
        .map_err(|error| format!("failed to write agent hook policy: {error}"))?;
    let config_path = codex_config_path(project_root, scope)?;
    if let Some(parent) = config_path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create Codex config dir: {error}"))?;
    }
    let existing_config = if config_path.exists() {
        fs::read_to_string(&config_path)
            .map_err(|error| format!("failed to read codex config.toml: {error}"))?
    } else {
        String::new()
    };
    fs::write(config_path, merge_agent_config_toml(&existing_config))
        .map_err(|error| format!("failed to write codex config.toml: {error}"))?;
    Ok(())
}

fn agent_config_toml() -> String {
    format!(
        r#"# Generated by `rs-harness agent install --client codex`.
#
unified_exec = true

{}
"#,
        rs_harness_agent_hooks_block()
    )
}

fn merge_agent_config_toml(existing: &str) -> String {
    let trimmed = existing.trim();
    if trimmed.is_empty() {
        return agent_config_toml();
    }

    let without_orphans = drop_orphan_hook_subsections(existing);
    let without_legacy = strip_legacy_rs_harness_hooks(&without_orphans);
    let with_unified_exec = ensure_unified_exec(&without_legacy);
    replace_or_append_managed_block(&with_unified_exec, &rs_harness_agent_hooks_block())
}

fn rs_harness_agent_hooks_block() -> String {
    format!(
        r#"{RS_HARNESS_BLOCK_BEGIN}
# Search-first flow:
# - Rust source reads are routed through rs-harness search packets.
# - Subagents should receive bounded search commands, not raw file inventories.
# - Pipe broad external candidates into `rs-harness search ingest items tests`.
# - Run one search command at a time; do not chain denied-read recovery commands.

[[hooks.SessionStart]]
matcher = "startup|resume|clear|compact"

[[hooks.SessionStart.hooks]]
type = "command"
timeout = 5
statusMessage = "Loading rs-harness search protocol"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex session-start "$repo_root"
'''

[[hooks.UserPromptSubmit]]

[[hooks.UserPromptSubmit.hooks]]
type = "command"
timeout = 5
statusMessage = "Planning rs-harness search flow"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex user-prompt "$repo_root"
'''

[[hooks.PreToolUse]]
matcher = "{CODEX_TOOL_MATCHER}"

[[hooks.PreToolUse.hooks]]
type = "command"
timeout = 5
statusMessage = "Checking rs-harness search flow"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex pre-tool "$repo_root"
'''

[[hooks.PermissionRequest]]
matcher = "{CODEX_TOOL_MATCHER}"

[[hooks.PermissionRequest.hooks]]
type = "command"
timeout = 5
statusMessage = "Checking rs-harness approval flow"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex permission-request "$repo_root"
'''

[[hooks.PostToolUse]]
matcher = "{CODEX_TOOL_MATCHER}"

[[hooks.PostToolUse.hooks]]
type = "command"
timeout = 5
statusMessage = "Updating rs-harness search flow state"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex post-tool "$repo_root"
'''

[[hooks.SubagentStart]]
matcher = ".*"

[[hooks.SubagentStart.hooks]]
type = "command"
timeout = 5
statusMessage = "Preparing rs-harness subagent context"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex subagent-start "$repo_root"
'''

[[hooks.SubagentStop]]
matcher = ".*"

[[hooks.SubagentStop.hooks]]
type = "command"
timeout = 5
statusMessage = "Checking rs-harness subagent evidence"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex subagent-stop "$repo_root"
'''

[[hooks.Stop]]

[[hooks.Stop.hooks]]
type = "command"
timeout = 5
statusMessage = "Checking rs-harness changed files"
command = '''
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
exec rs-harness agent hook --client codex stop "$repo_root"
'''
{RS_HARNESS_BLOCK_END}
"#
    )
}

fn ensure_unified_exec(config: &str) -> String {
    if config_has_unified_exec(config) {
        return ensure_trailing_newline(config.trim_end().to_string());
    }
    format!("unified_exec = true\n\n{}", config.trim_start())
}

fn replace_or_append_managed_block(config: &str, block: &str) -> String {
    let block = block.trim_end();
    let Some(start) = config.find(RS_HARNESS_BLOCK_BEGIN) else {
        return ensure_trailing_newline(format!("{}\n\n{block}", config.trim_end()));
    };
    let Some(end_offset) = config[start..].find(RS_HARNESS_BLOCK_END) else {
        return ensure_trailing_newline(format!("{}\n\n{block}", config.trim_end()));
    };
    let end = start + end_offset + RS_HARNESS_BLOCK_END.len();
    let rest_start = if config[end..].starts_with('\n') {
        end + 1
    } else {
        end
    };
    let before = config[..start].trim_end();
    let before = if is_legacy_rs_harness_preamble(before) {
        "unified_exec = true"
    } else {
        before
    };
    let after = config[rest_start..].trim_start_matches('\n').trim_end();
    let mut merged = String::new();
    if !before.is_empty() {
        merged.push_str(before);
        merged.push_str("\n\n");
    }
    merged.push_str(block);
    if !after.is_empty() {
        merged.push_str("\n\n");
        merged.push_str(after);
    }
    ensure_trailing_newline(merged)
}

fn strip_legacy_rs_harness_hooks(config: &str) -> String {
    if config.contains(RS_HARNESS_BLOCK_BEGIN)
        || !config.contains("rs-harness agent hook --client codex")
    {
        return ensure_trailing_newline(config.trim_end().to_string());
    }

    let sections = split_toml_hook_sections(config);
    let mut kept = Vec::new();
    for (index, section) in sections.iter().enumerate() {
        if index == 0 && is_legacy_rs_harness_preamble(&section.text) {
            continue;
        }
        if section
            .text
            .contains("rs-harness agent hook --client codex")
        {
            continue;
        }
        if let Some(event) = section.event_name()
            && sections.get(index + 1).is_some_and(|next| {
                next.hook_event_name().as_deref() == Some(event.as_str())
                    && next.text.contains("rs-harness agent hook --client codex")
            })
        {
            continue;
        }
        kept.push(section.text.trim_end());
    }
    drop_orphan_hook_subsections(&ensure_trailing_newline(
        kept.join("\n\n").trim().to_string(),
    ))
}

fn is_legacy_rs_harness_preamble(section: &str) -> bool {
    section.contains("# Generated by `rs-harness agent install --client codex`")
        && section.contains("Rust source reads are routed through rs-harness search packets")
}

struct TomlHookSection {
    text: String,
}

impl TomlHookSection {
    fn event_name(&self) -> Option<String> {
        parse_hook_header(self.header()?, false)
    }

    fn hook_event_name(&self) -> Option<String> {
        parse_hook_header(self.header()?, true)
    }

    fn header(&self) -> Option<&str> {
        self.text
            .lines()
            .find(|line| line.trim_start().starts_with("[[hooks."))
            .map(str::trim)
    }
}

fn split_toml_hook_sections(config: &str) -> Vec<TomlHookSection> {
    config
        .lines()
        .fold(TomlHookSectionBuilder::default(), |builder, line| {
            builder.push_line(line)
        })
        .finish()
}

#[derive(Default)]
struct TomlHookSectionBuilder {
    sections: Vec<TomlHookSection>,
    current: Vec<String>,
}

impl TomlHookSectionBuilder {
    fn push_line(mut self, line: &str) -> Self {
        if line.trim_start().starts_with("[[hooks.") && !self.current.is_empty() {
            self.sections.push(TomlHookSection {
                text: self.current.join("\n"),
            });
            self.current.clear();
        }
        self.current.push(line.to_string());
        self
    }

    fn finish(mut self) -> Vec<TomlHookSection> {
        if !self.current.is_empty() {
            self.sections.push(TomlHookSection {
                text: self.current.join("\n"),
            });
        }
        self.sections
    }
}

fn drop_orphan_hook_subsections(config: &str) -> String {
    let sections = split_toml_hook_sections(config);
    let kept = sections
        .into_iter()
        .fold(HookParentFilter::default(), |filter, section| {
            filter.push_section(section)
        })
        .finish();
    ensure_trailing_newline(kept.join("\n\n").trim().to_string())
}

#[derive(Default)]
struct HookParentFilter {
    seen_events: BTreeSet<String>,
    kept: Vec<String>,
}

impl HookParentFilter {
    fn push_section(mut self, section: TomlHookSection) -> Self {
        if let Some(event) = section.event_name() {
            self.seen_events.insert(event);
            self.kept.push(section.text.trim_end().to_string());
            return self;
        }
        if section
            .hook_event_name()
            .is_none_or(|event| self.seen_events.contains(&event))
        {
            self.kept.push(section.text.trim_end().to_string());
        }
        self
    }

    fn finish(self) -> Vec<String> {
        self.kept
    }
}

fn parse_hook_header(header: &str, nested_hook: bool) -> Option<String> {
    let event = header.strip_prefix("[[hooks.")?.strip_suffix("]]")?;
    if nested_hook {
        event.strip_suffix(".hooks").map(str::to_owned)
    } else if event.ends_with(".hooks") {
        None
    } else {
        Some(event.to_owned())
    }
}

fn ensure_trailing_newline(mut text: String) -> String {
    text.push('\n');
    text
}

pub(super) fn print_agent_doctor(
    project_root: &Path,
    action: &str,
    client: Option<&str>,
    scope: &AgentConfigScope,
) -> Result<(), String> {
    let Some(client) = client else {
        println!(
            "[agent-doctor] action={action} client=none skill=false policy=false config=false hooks=0 daemon=missing protocol=cli-cold"
        );
        println!(
            "|note kind=client-required message=\"pass --client codex to inspect Codex assets\""
        );
        return Ok(());
    };
    if client != "codex" {
        return Err(format!("unsupported agent client: {client}"));
    }
    let skill = project_root.join(CODEX_SKILL_DIR).join("SKILL.org");
    let policy = project_root.join(CODEX_POLICY_PATH);
    let config = codex_config_path(project_root, scope)?;
    let config_exists = config.exists();
    let config_text = if config_exists {
        fs::read_to_string(&config).unwrap_or_default()
    } else {
        String::new()
    };
    let unified_exec_present = config_has_unified_exec(&config_text);
    let namespaced_matcher_present = config_has_active_pretool_matcher(&config_text);
    let hooks = if config_exists {
        CODEX_CONFIG_HOOK_COUNT
    } else {
        0
    };
    if let Some(profile) = scope.profile_name() {
        println!(
            "[agent-doctor] action={action} client=codex scope={} profile={profile} skill={} policy={} config={} hooks={hooks} daemon=missing protocol=cli-cold",
            scope.label(),
            skill.exists(),
            policy.exists(),
            config_exists,
        );
    } else {
        println!(
            "[agent-doctor] action={action} client=codex skill={} policy={} config={} hooks={hooks} daemon=missing protocol=cli-cold",
            skill.exists(),
            policy.exists(),
            config_exists,
        );
    }
    println!(
        "|skill {} present={}",
        display_cli_path(project_root, &skill),
        skill.exists()
    );
    println!(
        "|policy {} present={}",
        display_cli_path(project_root, &policy),
        policy.exists()
    );
    println!(
        "|config {} present={}",
        display_config_path(project_root, &config, scope),
        config_exists
    );
    if let Some(profile) = scope.profile_name() {
        println!("|profile name={profile} usage=\"codex --profile {profile} exec -C <repo> ...\"");
        println!("|compat codex_exec_hooks runtime=requires-smoke-test enforced=unknown");
        println!(
            "|warn kind=codex-exec-hooks message=\"Codex CLI exec hook execution is runtime-dependent; verify with a smoke test before relying on profile enforcement\""
        );
    }
    if config_exists {
        println!("|compat unified_exec present={unified_exec_present} required=true");
        println!("|compat matcher namespaced={namespaced_matcher_present} required=true");
    }
    if config_exists && !unified_exec_present {
        println!(
            "|warn kind=codex-unified-exec message=\".codex/config.toml should set unified_exec = true for Desktop exec hooks\""
        );
    }
    if config_exists && !namespaced_matcher_present {
        println!(
            "|warn kind=codex-tool-matcher message=\"hook matcher should cover namespaced tools such as functions.exec_command\""
        );
    }
    for event in CODEX_CONFIG_HOOK_EVENTS {
        println!("|hook event={event} source=config present={config_exists}");
    }
    Ok(())
}

fn codex_config_path(project_root: &Path, scope: &AgentConfigScope) -> Result<PathBuf, String> {
    match scope {
        AgentConfigScope::Project => Ok(project_root.join(CODEX_CONFIG)),
        AgentConfigScope::CodexProfile(profile) => {
            Ok(codex_home()?.join(format!("{profile}.config.toml")))
        }
    }
}

fn codex_home() -> Result<PathBuf, String> {
    if let Some(home) = env::var_os("CODEX_HOME") {
        return Ok(PathBuf::from(home));
    }
    env::var_os("HOME")
        .map(|home| PathBuf::from(home).join(".codex"))
        .ok_or_else(|| "expected CODEX_HOME or HOME for Codex profile install".to_string())
}

fn validate_codex_profile_name(profile: &str) -> Result<(), String> {
    if !profile.is_empty()
        && profile
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
    {
        return Ok(());
    }
    Err(format!(
        "invalid Codex profile name: {profile}; expected ASCII letters, digits, '-' or '_'"
    ))
}

fn config_has_unified_exec(config: &str) -> bool {
    config
        .lines()
        .any(|line| line.trim() == "unified_exec = true")
}

fn config_has_active_pretool_matcher(config: &str) -> bool {
    let mut in_pre_tool = false;
    for line in config.lines().map(str::trim) {
        if line == "[[hooks.PreToolUse]]" {
            in_pre_tool = true;
            continue;
        }
        if line.starts_with("[[hooks.") {
            in_pre_tool = false;
        }
        if in_pre_tool && let Some(matcher) = line.strip_prefix("matcher = ") {
            return matcher.contains(".*(")
                && matcher.contains("exec_command")
                && matcher.contains("command_execution")
                && matcher.contains("fs\\\\.read")
                && matcher.contains("Read")
                && matcher.contains("Write")
                && !matcher.contains("disabled");
        }
    }
    false
}

fn display_cli_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .display()
        .to_string()
        .replace('\\', "/")
}

fn display_config_path(root: &Path, path: &Path, scope: &AgentConfigScope) -> String {
    if matches!(scope, AgentConfigScope::Project) {
        return display_cli_path(root, path);
    }
    path.display().to_string().replace('\\', "/")
}
