//! Agent-oriented Rust policy rules.

mod algorithm_shape;
mod api_shape;
mod data_shape;
pub(crate) mod dependency_graph;
mod doc_boundary;
mod native_abi;
mod pack;
mod process_command;
mod scenario_requirements;
mod source_surface;
mod tokio_runtime;

pub use pack::rust_agent_policy_rules;
use pack::{
    RUST_AGENT_POLICY_API_ERROR_BOUNDARY_V1, RUST_AGENT_POLICY_API_FACADE_EXPORT_GROUPS_V1,
    RUST_AGENT_POLICY_API_FLAG_PARAMETER_SURFACE_V1,
    RUST_AGENT_POLICY_API_POSITIONAL_PARAMETER_SURFACE_V1,
    RUST_AGENT_POLICY_API_PRIMITIVE_TYPE_ALIAS_V1, RUST_AGENT_POLICY_API_PUBLIC_NAME_CONFLICT_V1,
    RUST_AGENT_POLICY_API_SEMANTIC_IDENTIFIER_TYPE_V1,
    RUST_AGENT_POLICY_ASYNC_BACKPRESSURE_BOUNDARY_V1, RUST_AGENT_POLICY_ASYNC_BLOCKING_BOUNDARY_V1,
    RUST_AGENT_POLICY_ASYNC_SELECT_CANCEL_SAFETY_V1, RUST_AGENT_POLICY_ASYNC_SYNC_LOCK_BOUNDARY_V1,
    RUST_AGENT_POLICY_ASYNC_TASK_LIFECYCLE_V1, RUST_AGENT_POLICY_ASYNC_TIMEOUT_CANCEL_SAFETY_V1,
    RUST_AGENT_POLICY_CFG_IMPL_NESTED_TRAVERSAL_V1, RUST_AGENT_POLICY_CFG_PUBLIC_BROAD_SURFACE_V1,
    RUST_AGENT_POLICY_CFG_PUBLIC_NESTED_FLOW_V1, RUST_AGENT_POLICY_DATA_DERIVABLE_BOUNDS_V1,
    RUST_AGENT_POLICY_DATA_ENUM_PRIMITIVE_PAYLOAD_V1, RUST_AGENT_POLICY_DATA_ENUM_TUPLE_PAYLOAD_V1,
    RUST_AGENT_POLICY_DATA_LINEAR_MEMBERSHIP_SCAN_V1, RUST_AGENT_POLICY_DATA_PRIMITIVE_FIELD_V1,
    RUST_AGENT_POLICY_DATA_STRINGLY_STATE_FIELD_V1, RUST_AGENT_POLICY_DOCS_BRANCH_INTENT_V1,
    RUST_AGENT_POLICY_DOCS_MODULE_INTENT_V1, RUST_AGENT_POLICY_DOCS_OWNER_FAN_OUT_V1,
    RUST_AGENT_POLICY_DOCS_PUBLIC_ITEM_V1, RUST_AGENT_POLICY_ITER_IMPL_MANUAL_TRANSFORM_V1,
    RUST_AGENT_POLICY_ITER_PUBLIC_MANUAL_TRANSFORM_V1, RUST_AGENT_POLICY_NATIVE_ABI_CONTRACT_V1,
    RUST_AGENT_POLICY_OWNER_DEPENDENCY_CYCLE_V1, RUST_AGENT_POLICY_OWNER_LEAF_IMPORT_V1,
    RUST_AGENT_POLICY_PROCESS_COMMAND_PROBE_V1,
    RUST_AGENT_POLICY_PUBLIC_DYNAMIC_JSON_API_BOUNDARY_V1,
    RUST_AGENT_POLICY_PUBLIC_TUPLE_API_SURFACE_V1, RUST_AGENT_POLICY_SOURCE_MODULE_PATH_NAME_V1,
    RUST_AGENT_POLICY_SOURCE_NAMESPACE_REPEAT_V1, RUST_AGENT_POLICY_SOURCE_PUBLIC_MODULE_NAME_V1,
    RUST_AGENT_POLICY_TEST_SUPPORT_REEXPORT_V1, RUST_AGENT_POLICY_TOKIO_RUNTIME_BOUNDARY_V1,
};
pub(crate) use pack::{evaluate, rust_agent_policy_scenario_requirements};
